{
    "name": "DogForce Zambia Demo Site Suite",
    "version": "19.0.1.0.0",
    "category": "Security/Demo",
    "summary": "Master meta-module for Sentinel Security Services Zambia Demo Site on Alibaba Cloud Server.",
    "description": """
        DogForce Security Services — Alibaba Cloud Zambia Demo Site Suite:
        - Meta-installer that aggregates all active Zambian security modules.
        - Includes security_suite, security_l10n_zm, security_zra_invoice, security_demo_data_zm,
          security_demo_site, security_shift_planner, and security_ai_whatsapp_bridge.
        - Used for single-command database updates on demo instances (zambia-demo & dogforce_dev).
        - EXCLUDED from Namibia Production deployments (199.192.23.46).
    """,
    "author": "Google DeepMind team working on Advanced Agentic Coding",
    "license": "LGPL-3",
    "depends": [
        "security_accounting_controls",
        "security_ai_engine",
        "security_ai_whatsapp_bridge",
        "security_attendance",
        "security_backup_vault",
        "security_base",
        "security_billing",
        "security_billing_account",
        "security_billing_crm",
        "security_billing_sale",
        "security_client_onboarding",
        "security_client_reports",
        "security_compliance_roster",
        "security_discipline",
        "security_discipline_payroll",
        "security_documents",
        "security_dogforce_data",
        "security_dogforce_migration",
        "security_equipment",
        "security_equipment_payroll",
        "security_fleet",
        "security_fleet_ops",
        "security_help",
        "security_l10n_zm",
        "security_leave",
        "security_licensing",
        "security_loans",
        "security_mobile",
        "security_mobile_bridge",
        "security_notifications",
        "security_operations",
        "security_operations_crm",
        "security_payroll_core",
        "security_portal",
        "security_reporting",
        "security_shift_planner",
        "security_theme",
        "security_tour",
        "security_zra_invoice",
        "security_demo_data_zm",
        "security_demo_site",
    ],
    "data": [],
    "assets": {},
    "installable": True,
    "application": True,
    "auto_install": False,
}
