import logging
import secrets

from . import models

_logger = logging.getLogger(__name__)


def post_init_hook(env):
    """Create the DeployGuard Integration user and its first config record.

    No fixed password is ever written anywhere -- not in this file, not in
    XML data. This user authenticates to the Platform exclusively via an
    Odoo API key (res.users.apikeys), generated by hand after install
    (docs/deployguard/12-odoo-integration.md §2 step 3). The random password
    set here only satisfies res.users' requirement that one exist; it is
    never surfaced, logged, or intended to be used, and interactive login
    with it is not a supported path.
    """
    group = env.ref("security_deployguard_bridge.group_deployguard_integration")

    existing = env["res.users"].with_context(active_test=False).search(
        [("login", "=", "deployguard.integration")], limit=1
    )
    if existing:
        integration_user = existing
    else:
        integration_user = env["res.users"].create({
            "name": "DeployGuard Integration",
            "login": "deployguard.integration",
            "password": secrets.token_urlsafe(48),
            "group_ids": [(6, 0, [group.id])],
            "active": True,
        })
        _logger.info(
            "DeployGuard Bridge: created integration user %s (id=%s). "
            "Generate an API key for it under that user's My Profile > "
            "Account Security, then paste it into the DeployGuard Platform's "
            "Odoo integration settings -- see docs/deployguard/"
            "12-odoo-integration.md §2.",
            integration_user.login, integration_user.id,
        )

    if not env["security.deployguard.config"].sudo().search([], limit=1):
        env["security.deployguard.config"].sudo().create({
            "name": "DeployGuard Bridge Configuration",
            "integration_user_id": integration_user.id,
        })
