[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = admin123
db_host = dpg-d8hu5gtdt1ts73enc480-a.singapore-postgres.render.com
db_port = 5432
db_user = odoo
db_password = umDKFz8bHRvq7ZGy7nJlYznWoZq1ZW7l
db_name = dogforce_dev
http_port = 8069
logfile = /dev/stdout
log_level = info
proxy_mode = True
