{
    "name": "Security Payroll Core",
    "summary": "Core payroll periods, payslips, earnings, and deductions for security operations",
    "version": "19.0.1.0.0",
    "category": "Human Resources",
    "author": "Winston Zulu",
    "license": "LGPL-3",
    "depends": ["security_l10n_na", "web"],
    "data": [
        "security/ir.model.access.csv",
        "views/security_payroll_core_views.xml",
        "views/security_payroll_wizard_views.xml",
        "views/security_payroll_command_center_actions.xml",
        "views/security_payroll_expenditure_actions.xml",
        "views/security_payroll_l10n_buttons.xml",
        "views/security_payroll_employee_history.xml",
        "reports/security_payslip_report.xml",
        "reports/security_payroll_management_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "security_payroll_core/static/src/js/payslip_preview.js",
            "security_payroll_core/static/src/xml/payslip_preview.xml",
            "security_payroll_core/static/src/js/payroll_command_center.js",
            "security_payroll_core/static/src/xml/payroll_command_center.xml",
            "security_payroll_core/static/src/css/payroll_command_center.css",
            "security_payroll_core/static/src/js/payroll_expenditure.js",
            "security_payroll_core/static/src/xml/payroll_expenditure.xml",
        ],
    },
    "installable": True,
    "application": False,
}
