from datetime import timedelta

from odoo import api, fields, models


class SecuritySlotSuggestion(models.Model):
    """
    Ranked guard suggestion for an unassigned roster slot.

    Generated by SecurityRosterSlot.action_suggest_guards().
    Cleared and regenerated each time suggestions are refreshed.
    """
    _name = "security.slot.suggestion"
    _description = "Guard Suggestion for Roster Slot"
    _order = "rank, score desc"

    slot_id = fields.Many2one(
        "security.roster.slot",
        required=True,
        ondelete="cascade",
    )
    employee_id = fields.Many2one("hr.employee", required=True)
    employee_grade_id = fields.Many2one(related="employee_id.security_grade_id", store=True)
    rank = fields.Integer(default=0)
    score = fields.Float(default=0.0)
    score_breakdown = fields.Text(readonly=True)

    def action_assign_to_slot(self):
        for suggestion in self:
            slot = suggestion.slot_id
            employee = suggestion.employee_id
            reason = self._check_assignment_eligibility(slot, employee)
            if reason:
                return {
                    "type": "ir.actions.client",
                    "tag": "display_notification",
                    "params": {
                        "title": f"Cannot Assign {employee.name}",
                        "message": reason,
                        "type": "danger",
                        "sticky": True,
                    },
                }
            slot.employee_id = employee
            slot.state = "assigned"

    def _check_assignment_eligibility(self, slot, employee):
        """Return a human-readable reason string if ineligible, else None."""
        if not employee.active:
            return f"{employee.name} is no longer active."
        if employee.security_disqualified:
            return f"{employee.name} is disqualified from duty."
        if not employee.security_guard:
            return f"{employee.name} is not registered as a security guard."
        # Grade check
        post_type = slot.post_id.post_type_id if slot.post_id else False
        if post_type and post_type.min_grade_id:
            emp_seq = employee.security_grade_id.sequence if employee.security_grade_id else 0
            if emp_seq < post_type.min_grade_id.sequence:
                return (
                    f"{employee.name} is Grade {employee.security_grade_id.name or 'None'} "
                    f"but this post requires at least Grade {post_type.min_grade_id.name}."
                )
        # On leave
        leave_model = self.env.get("security.leave.request")
        if leave_model and slot.shift_date:
            if leave_model.search_count([
                ("employee_id", "=", employee.id),
                ("state", "=", "approved"),
                ("date_from", "<=", slot.shift_date),
                ("date_to", ">=", slot.shift_date),
            ]):
                return f"{employee.name} has approved leave on {slot.shift_date}."
        # Double-booking
        if self.env["security.roster.slot"].search_count([
            ("shift_date", "=", slot.shift_date),
            ("employee_id", "=", employee.id),
            ("state", "not in", ["cancelled"]),
            ("id", "!=", slot.id),
        ]):
            return f"{employee.name} is already assigned to another post on {slot.shift_date}."
        # Site/client exclusion
        site_id = slot.site_id.id if slot.site_id else False
        partner_id = slot.partner_id.id if slot.partner_id else False
        if site_id or partner_id:
            exclusion = self.env["security.guard.exclusion"].search([
                ("employee_id", "=", employee.id),
                ("active", "=", True),
                "|",
                ("site_id", "=", site_id),
                ("partner_id", "=", partner_id),
            ], limit=1)
            if exclusion:
                target = exclusion.site_id.name or exclusion.partner_id.name or "this location"
                return (
                    f"{employee.name} is excluded from {target}. "
                    f"Reason: {exclusion.reason or 'no reason recorded'}."
                )
        # Missing certifications
        required_cert_ids = set()
        if post_type:
            required_cert_ids |= set(post_type.required_certification_ids.ids)
        if slot.shift_requirement_id:
            required_cert_ids |= set(slot.shift_requirement_id.required_certification_ids.ids)
        missing = required_cert_ids - set(employee.security_certification_ids.ids)
        if missing:
            names = self.env["security.certification"].browse(list(missing)).mapped("name")
            return f"{employee.name} is missing: {', '.join(names)}."
        return None


class SecurityRosterBatch(models.Model):
    _inherit = "security.roster.batch"

    @api.model
    def action_quick_create_batch(self, partner_id=False, site_id=False, date_from=False, date_to=False):
        """Create a batch and generate slots in one call — used by the Roster Board create dialog."""
        vals = {"date_from": date_from, "date_to": date_to}
        if site_id:
            vals["site_id"] = site_id
            site = self.env["security.client.site"].browse(site_id)
            vals["partner_id"] = site.partner_id.id
        elif partner_id:
            vals["partner_id"] = partner_id
        batch = self.create(vals)
        batch.action_generate_slots()
        return {
            "batch_id": batch.id,
            "batch_name": batch.name,
            "slot_count": len(batch.slot_ids),
        }

    unassigned_count = fields.Integer(
        compute="_compute_gap_counts",
        string="Unassigned Slots",
    )
    critical_gap_count = fields.Integer(
        compute="_compute_gap_counts",
        string="Critical Gaps",
    )
    fill_rate = fields.Float(
        compute="_compute_gap_counts",
        string="Fill Rate (%)",
        digits=(5, 1),
    )

    @api.depends("slot_ids.employee_id", "slot_ids.state", "slot_ids.critical_gap")
    def _compute_gap_counts(self):
        for batch in self:
            active = batch.slot_ids.filtered(lambda s: s.state != "cancelled")
            unassigned = active.filtered(lambda s: not s.employee_id)
            batch.unassigned_count = len(unassigned)
            batch.critical_gap_count = len(unassigned.filtered(lambda s: s.critical_gap))
            total = len(active)
            assigned = total - len(unassigned)
            batch.fill_rate = round(assigned / total * 100, 1) if total else 0.0

    def action_auto_fill_slots(self):
        """
        Greedy auto-fill: assigns the highest-scoring eligible guard to each
        unassigned slot, processing high-value shifts first.

        assigned_today tracks within-run assignments to prevent double-booking.

        NOTE: rest-hour constraints between slots filled in the same run are not
        enforced here. Add a _is_still_eligible() check after each assignment
        once rest-hour rules are implemented on SecurityRosterSlot (Phase 2).

        Notification create calls use sudo() to avoid cascading writes if a
        write listener on security.attendance.record recomputes batch fields and
        tries to trigger further notifications (no_notify context pattern).
        """
        filled = 0
        gaps = 0
        for batch in self:
            unassigned = batch.slot_ids.filtered(
                lambda s: not s.employee_id and s.state != "cancelled"
            )
            # High-value shifts first, then by date and shift start time
            unassigned = unassigned.sorted(
                key=lambda s: (
                    not s.high_value_shift,
                    str(s.shift_date) if s.shift_date else "",
                    s.shift_template_id.start_hour if s.shift_template_id else 0,
                )
            )
            # {shift_date_str: set(employee_id)} — prevents double-booking in this run
            assigned_today = {}
            for slot in unassigned:
                slot.critical_gap = False
                eligible = slot._get_eligible_guards(slot)
                if not eligible:
                    slot.critical_gap = True
                    gaps += 1
                    continue
                # Exclude guards assigned in this run (DB query is already done in
                # _get_eligible_guards; assigned_today covers intra-run assignments)
                date_key = str(slot.shift_date)
                run_assigned = assigned_today.get(date_key, set())
                eligible = [(emp, sc) for emp, sc in eligible if emp.id not in run_assigned]
                if not eligible:
                    slot.critical_gap = True
                    gaps += 1
                    continue
                # Score remaining candidates and assign the best
                scored = []
                for employee, _ in eligible:
                    score, _breakdown = slot._score_guard(slot, employee)
                    scored.append((score, employee))
                scored.sort(key=lambda x: x[0], reverse=True)
                _best_score, best_employee = scored[0]
                slot.employee_id = best_employee.id
                slot.state = "assigned"
                slot.critical_gap = False
                assigned_today.setdefault(date_key, set()).add(best_employee.id)
                filled += 1
            if gaps and "security.notification" in self.env:
                manager_group = self.env.ref(
                    "security_base.group_security_manager", raise_if_not_found=False
                )
                if manager_group:
                    manager_users = self.env["res.users"].search(
                        [("groups_id", "in", [manager_group.id])]
                    )
                else:
                    manager_users = self.env["res.users"].browse()
                self.env["security.notification"].sudo().create({
                    "title": f"Auto-Fill: {gaps} Critical Gap(s) — {batch.name}",
                    "body": (
                        f"Auto-fill for '{batch.name}' left {gaps} slot(s) unfilled — "
                        "no eligible guard was available. "
                        "Review the red cells in the Roster Board and assign manually."
                    ),
                    "notification_type": "roster_gap",
                    "severity": "critical",
                    "recipient_ids": [(6, 0, manager_users.ids)],
                    "related_model": "security.roster.batch",
                    "related_id": batch.id,
                })
        msg = f"{filled} slot(s) filled automatically."
        if gaps:
            msg += f" {gaps} critical gap(s) could not be filled — review red cells."
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": "Auto-Fill Complete",
                "message": msg,
                "type": "success" if not gaps else "warning",
                "sticky": gaps > 0,
            },
        }


class SecurityRosterSlot(models.Model):
    _inherit = "security.roster.slot"

    suggestion_ids = fields.One2many(
        "security.slot.suggestion",
        "slot_id",
        string="Guard Suggestions",
    )
    suggestion_count = fields.Integer(compute="_compute_suggestion_count")
    critical_gap = fields.Boolean(
        default=False,
        string="Critical Gap",
        help="Set by auto-fill when no eligible guard was found for this slot.",
    )

    def _compute_suggestion_count(self):
        for slot in self:
            slot.suggestion_count = len(slot.suggestion_ids)

    def action_suggest_guards(self):
        """
        Score and rank all eligible guards for this unassigned slot.

        Scoring weights (max 150 pts):
          +reliability_score          (0-100)  Guard's base reliability score
          +20 site familiarity         if guard worked this site in last 45 days
          +10 grade bonus              if guard's grade sequence is higher than minimum
          -5 per shift this period     (fairness — cap at -30, so max 6 shifts penalty)
          -10 awol or absence flag     if guard had AWOL in last 30 days
          -20 double-booking           excluded — handled by eligibility filter
        """
        for slot in self:
            slot.suggestion_ids.unlink()
            eligible = self._get_eligible_guards(slot)
            if not eligible:
                continue

            suggestions = []
            for employee, ineligibility_score in eligible:
                score, breakdown = self._score_guard(slot, employee)
                suggestions.append((score, employee, breakdown))

            suggestions.sort(key=lambda x: x[0], reverse=True)
            suggestion_vals = []
            for rank, (score, employee, breakdown) in enumerate(suggestions, start=1):
                suggestion_vals.append({
                    "slot_id": slot.id,
                    "employee_id": employee.id,
                    "rank": rank,
                    "score": score,
                    "score_breakdown": breakdown,
                })
            if suggestion_vals:
                self.env["security.slot.suggestion"].create(suggestion_vals)

    def _get_eligible_guards(self, slot):
        """
        Return list of (employee, 0) tuples for guards that pass all hard constraints.

        Hard constraints (any failure → exclude):
          1. Active security guard, not disqualified
          2. Not excluded from this site or client
          3. Meets minimum grade requirement
          4. Holds all required certifications (none expired)
          5. Not on approved leave on shift_date
          6. Not already assigned to another slot on shift_date
        """
        employee_model = self.env["hr.employee"]
        all_guards = employee_model.search([
            ("security_guard", "=", True),
            ("active", "=", True),
            ("security_disqualified", "=", False),
        ])

        post_type = slot.post_id.post_type_id
        requirement = slot.shift_requirement_id
        site_id = slot.site_id.id or False
        partner_id = slot.partner_id.id or False

        required_certs = set(post_type.required_certification_ids.ids)
        if requirement:
            required_certs |= set(requirement.required_certification_ids.ids)

        min_grade_seq = post_type.min_grade_id.sequence if post_type.min_grade_id else 0
        min_score = max(
            post_type.minimum_reliability_score,
            requirement.minimum_reliability_score if requirement else 0,
        )

        # Pre-fetch approved leave requests for shift_date
        leave_model = self.env["security.leave.request"] if "security.leave.request" in self.env else False
        guards_on_leave = set()
        if leave_model and slot.shift_date:
            leaves = leave_model.search([
                ("state", "=", "approved"),
                ("date_from", "<=", slot.shift_date),
                ("date_to", ">=", slot.shift_date),
            ])
            guards_on_leave = set(leaves.mapped("employee_id").ids)

        # Pre-fetch guards already assigned on shift_date (double-booking check)
        already_assigned = set(self.search([
            ("shift_date", "=", slot.shift_date),
            ("employee_id", "!=", False),
            ("state", "not in", ("cancelled",)),
            ("id", "!=", slot.id),
        ]).mapped("employee_id").ids)

        # Pre-fetch exclusions for this site/client
        exclusion_model = self.env["security.guard.exclusion"]
        excluded_guard_ids = set()
        if site_id or partner_id:
            domain = [("active", "=", True), "|"]
            if site_id:
                domain.append(("site_id", "=", site_id))
            else:
                domain.append(("site_id", "=", False))
            if partner_id:
                domain.append(("partner_id", "=", partner_id))
            else:
                domain.append(("partner_id", "=", False))
            excluded_guard_ids = set(exclusion_model.search([
                ("active", "=", True),
                "|",
                ("site_id", "=", site_id),
                ("partner_id", "=", partner_id),
            ]).mapped("employee_id").ids)

        eligible = []
        for employee in all_guards:
            # Guard on leave
            if employee.id in guards_on_leave:
                continue
            # Already assigned elsewhere
            if employee.id in already_assigned:
                continue
            # Excluded from site/client
            if employee.id in excluded_guard_ids:
                continue
            # Grade check
            if min_grade_seq > 0:
                emp_grade_seq = employee.security_grade_id.sequence if employee.security_grade_id else 0
                if emp_grade_seq < min_grade_seq:
                    continue
            # Reliability score
            if employee.security_reliability_score < min_score:
                continue
            # Certifications
            emp_cert_ids = set(employee.security_certification_ids.ids)
            if required_certs - emp_cert_ids:
                continue
            # Expired certifications (if documents module is installed)
            if hasattr(employee, "get_expired_certification_ids"):
                expired = employee.get_expired_certification_ids()
                if required_certs & expired:
                    continue

            # Check required documents for the post type
            post_type_for_docs = slot.post_id.post_type_id if slot.post_id and slot.post_id.post_type_id else False
            if post_type_for_docs and hasattr(post_type_for_docs, "required_document_type_ids") and post_type_for_docs.required_document_type_ids:
                today = fields.Date.context_today(self)
                doc_model = self.env.get("security.employee.document")
                if doc_model is not None:
                    doc_missing = False
                    for required_type in post_type_for_docs.required_document_type_ids:
                        has_valid_doc = doc_model.search_count([
                            ("employee_id", "=", employee.id),
                            ("document_type_id", "=", required_type.id),
                            ("state", "=", "verified"),
                            "|",
                            ("expiry_date", "=", False),
                            ("expiry_date", ">=", str(today)),
                        ])
                        if not has_valid_doc:
                            doc_missing = True
                            break
                    if doc_missing:
                        continue

            eligible.append((employee, 0))

        return eligible

    def _score_guard(self, slot, employee):
        """Return (score, breakdown_text) for one eligible guard."""
        score = float(employee.security_reliability_score)
        parts = [f"Reliability: {score:.0f}"]

        # Site familiarity bonus
        attendance_model = self.env["security.attendance.record"]
        if slot.shift_date and slot.site_id:
            look_back = slot.shift_date - timedelta(days=45)
            familiarity_count = attendance_model.search_count([
                ("employee_id", "=", employee.id),
                ("site_id", "=", slot.site_id.id),
                ("shift_date", ">=", look_back),
                ("shift_date", "<", slot.shift_date),
                ("status", "in", ["present", "late", "early_leave"]),
            ])
            if familiarity_count > 0:
                score += 20
                parts.append(f"+20 site familiarity ({familiarity_count} recent shifts)")

        # Grade bonus (guard is better-qualified than minimum)
        if slot.post_id.post_type_id.min_grade_id and employee.security_grade_id:
            min_seq = slot.post_id.post_type_id.min_grade_id.sequence
            emp_seq = employee.security_grade_id.sequence
            if emp_seq > min_seq:
                score += 10
                parts.append("+10 above minimum grade")

        # Fairness penalty (shifts already in this batch)
        if slot.batch_id:
            shifts_this_period = self.search_count([
                ("batch_id", "=", slot.batch_id.id),
                ("employee_id", "=", employee.id),
                ("state", "not in", ("cancelled",)),
                ("id", "!=", slot.id),
            ])
            penalty = min(shifts_this_period * 5, 30)
            if penalty > 0:
                score -= penalty
                parts.append(f"-{penalty} fairness ({shifts_this_period} shifts this period)")

        # AWOL / absence penalty
        attendance_model_avail = self.env["security.attendance.record"]
        if slot.shift_date:
            look_back_awol = slot.shift_date - timedelta(days=30)
            awol_count = attendance_model_avail.search_count([
                ("employee_id", "=", employee.id),
                ("shift_date", ">=", look_back_awol),
                ("absence_type", "=", "awol"),
            ])
            if awol_count > 0:
                penalty = min(awol_count * 10, 30)
                score -= penalty
                parts.append(f"-{penalty} AWOL in last 30 days ({awol_count}x)")

        return max(0.0, score), " | ".join(parts)

    def action_log_override(self, reason):
        """
        Record a manual override on the slot: write override_reason and append
        a timestamped entry to the note field for the full audit trail.
        """
        now = fields.Datetime.now()
        user_name = self.env.user.name
        for slot in self:
            slot.override_reason = reason or ""
            entry = f"[{now.strftime('%Y-%m-%d %H:%M')} UTC] Override by {user_name}: {reason or '(no reason given)'}"
            slot.note = (slot.note + "\n" + entry).strip() if slot.note else entry
