from datetime import timedelta

from odoo import api, fields, models


class SecuritySlotSuggestion(models.Model):
    """
    Ranked guard suggestion for an unassigned roster slot.

    Generated by SecurityRosterSlot.action_suggest_guards().
    Cleared and regenerated each time suggestions are refreshed.
    """
    _name = "security.slot.suggestion"
    _description = "Guard Suggestion for Roster Slot"
    _order = "rank, score desc"

    slot_id = fields.Many2one(
        "security.roster.slot",
        required=True,
        ondelete="cascade",
    )
    employee_id = fields.Many2one("hr.employee", required=True)
    employee_grade_id = fields.Many2one(related="employee_id.security_grade_id", store=True)
    rank = fields.Integer(default=0)
    score = fields.Float(default=0.0)
    score_breakdown = fields.Text(readonly=True)

    def action_assign_to_slot(self):
        for suggestion in self:
            slot = suggestion.slot_id
            employee = suggestion.employee_id
            reason = self._check_assignment_eligibility(slot, employee)
            if reason:
                return {
                    "type": "ir.actions.client",
                    "tag": "display_notification",
                    "params": {
                        "title": f"Cannot Assign {employee.name}",
                        "message": reason,
                        "type": "danger",
                        "sticky": True,
                    },
                }
            slot.employee_id = employee
            slot.state = "assigned"

    def _check_assignment_eligibility(self, slot, employee):
        """Return a human-readable reason string if ineligible, else None."""
        if not employee.active:
            return f"{employee.name} is no longer active."
        if employee.security_disqualified:
            return f"{employee.name} is disqualified from duty."
        if not employee.security_guard:
            return f"{employee.name} is not registered as a security guard."
        # Grade check
        post_type = slot.post_id.post_type_id if slot.post_id else False
        if post_type and post_type.min_grade_id:
            emp_seq = employee.security_grade_id.sequence if employee.security_grade_id else 0
            if emp_seq < post_type.min_grade_id.sequence:
                return (
                    f"{employee.name} is Grade {employee.security_grade_id.name or 'None'} "
                    f"but this post requires at least Grade {post_type.min_grade_id.name}."
                )
        # On leave
        leave_model = self.env.get("security.leave.request")
        if leave_model and slot.shift_date:
            if leave_model.search_count([
                ("employee_id", "=", employee.id),
                ("state", "=", "approved"),
                ("date_from", "<=", slot.shift_date),
                ("date_to", ">=", slot.shift_date),
            ]):
                return f"{employee.name} has approved leave on {slot.shift_date}."
        # Double-booking
        if self.env["security.roster.slot"].search_count([
            ("shift_date", "=", slot.shift_date),
            ("employee_id", "=", employee.id),
            ("state", "not in", ["cancelled"]),
            ("id", "!=", slot.id),
        ]):
            return f"{employee.name} is already assigned to another post on {slot.shift_date}."
        # Site/client exclusion
        site_id = slot.site_id.id if slot.site_id else False
        partner_id = slot.partner_id.id if slot.partner_id else False
        if site_id or partner_id:
            exclusion = self.env["security.guard.exclusion"].search([
                ("employee_id", "=", employee.id),
                ("active", "=", True),
                "|",
                ("site_id", "=", site_id),
                ("partner_id", "=", partner_id),
            ], limit=1)
            if exclusion:
                target = exclusion.site_id.name or exclusion.partner_id.name or "this location"
                return (
                    f"{employee.name} is excluded from {target}. "
                    f"Reason: {exclusion.reason or 'no reason recorded'}."
                )
        # Missing certifications
        required_cert_ids = set()
        if post_type:
            required_cert_ids |= set(post_type.required_certification_ids.ids)
        if slot.shift_requirement_id:
            required_cert_ids |= set(slot.shift_requirement_id.required_certification_ids.ids)
        missing = required_cert_ids - set(employee.security_certification_ids.ids)
        if missing:
            names = self.env["security.certification"].browse(list(missing)).mapped("name")
            return f"{employee.name} is missing: {', '.join(names)}."
        return None


class SecurityRosterSlot(models.Model):
    _inherit = "security.roster.slot"

    suggestion_ids = fields.One2many(
        "security.slot.suggestion",
        "slot_id",
        string="Guard Suggestions",
    )
    suggestion_count = fields.Integer(compute="_compute_suggestion_count")

    def _compute_suggestion_count(self):
        for slot in self:
            slot.suggestion_count = len(slot.suggestion_ids)

    def action_suggest_guards(self):
        """
        Score and rank all eligible guards for this unassigned slot.

        Scoring weights (max 150 pts):
          +reliability_score          (0-100)  Guard's base reliability score
          +20 site familiarity         if guard worked this site in last 45 days
          +10 grade bonus              if guard's grade sequence is higher than minimum
          -5 per shift this period     (fairness — cap at -30, so max 6 shifts penalty)
          -10 awol or absence flag     if guard had AWOL in last 30 days
          Guards who score exactly 0 after all adjustments are excluded from suggestions.
        """
        for slot in self:
            slot.suggestion_ids.unlink()
            eligible = self._get_eligible_guards(slot)
            if not eligible:
                continue

            suggestions = []
            for employee, _unused in eligible:
                score, breakdown = self._score_guard(slot, employee)
                suggestions.append((score, employee, breakdown))

            # Exclude guards who scored zero — they have no positive signal
            suggestions = [(s, e, b) for s, e, b in suggestions if s > 0]
            suggestions.sort(key=lambda x: x[0], reverse=True)

            suggestion_vals = []
            for rank, (score, employee, breakdown) in enumerate(suggestions, start=1):
                suggestion_vals.append({
                    "slot_id": slot.id,
                    "employee_id": employee.id,
                    "rank": rank,
                    "score": score,
                    "score_breakdown": breakdown,
                })
            if suggestion_vals:
                self.env["security.slot.suggestion"].create(suggestion_vals)

    # Minimum score a suggestion must reach for auto-assignment (amber threshold)
    AUTO_ASSIGN_MIN_SCORE = 50.0

    def action_auto_assign_all(self):
        """
        Auto-assign the top-ranked eligible guard to every unassigned slot in self.

        Only assigns when the top suggestion scores >= AUTO_ASSIGN_MIN_SCORE so that
        very low-quality matches are left for manual review. Returns a summary
        notification that can be displayed directly by the JS caller.
        """
        assigned = 0
        no_candidates = 0
        below_threshold = 0

        for slot in self:
            if slot.state == "cancelled" or slot.employee_id:
                continue

            slot.action_suggest_guards()

            top = self.env["security.slot.suggestion"].search(
                [("slot_id", "=", slot.id)],
                order="rank",
                limit=1,
            )

            if not top:
                no_candidates += 1
                continue

            if top.score < self.AUTO_ASSIGN_MIN_SCORE:
                below_threshold += 1
                continue

            reason = top._check_assignment_eligibility(slot, top.employee_id)
            if reason:
                no_candidates += 1
                continue

            slot.employee_id = top.employee_id
            slot.state = "assigned"
            assigned += 1

        parts = [f"{assigned} slot(s) auto-assigned"]
        if no_candidates:
            parts.append(f"{no_candidates} had no eligible candidates")
        if below_threshold:
            parts.append(f"{below_threshold} skipped (best score below {int(self.AUTO_ASSIGN_MIN_SCORE)} pts — review manually)")

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": "Auto-Assignment Complete",
                "message": ". ".join(parts) + ".",
                "type": "success" if assigned > 0 else "warning",
                "sticky": False,
            },
        }

    def _get_eligible_guards(self, slot):
        """
        Return list of (employee, 0) tuples for guards that pass all hard constraints.

        Hard constraints (any failure → exclude):
          1. Active security guard, not disqualified
          2. Not excluded from this site or client
          3. Meets minimum grade requirement
          4. Holds all required certifications (none expired)
          5. Not on approved leave on shift_date
          6. Not already assigned to another slot on shift_date
        """
        employee_model = self.env["hr.employee"]
        all_guards = employee_model.search([
            ("security_guard", "=", True),
            ("active", "=", True),
            ("security_disqualified", "=", False),
        ])

        post_type = slot.post_id.post_type_id
        requirement = slot.shift_requirement_id
        site_id = slot.site_id.id or False
        partner_id = slot.partner_id.id or False

        required_certs = set(post_type.required_certification_ids.ids)
        if requirement:
            required_certs |= set(requirement.required_certification_ids.ids)

        min_grade_seq = post_type.min_grade_id.sequence if post_type.min_grade_id else 0
        min_score = max(
            post_type.minimum_reliability_score,
            requirement.minimum_reliability_score if requirement else 0,
        )

        # Pre-fetch approved leave requests for shift_date
        leave_model = self.env["security.leave.request"] if "security.leave.request" in self.env else False
        guards_on_leave = set()
        if leave_model and slot.shift_date:
            leaves = leave_model.search([
                ("state", "=", "approved"),
                ("date_from", "<=", slot.shift_date),
                ("date_to", ">=", slot.shift_date),
            ])
            guards_on_leave = set(leaves.mapped("employee_id").ids)

        # Pre-fetch guards already assigned on shift_date (double-booking check)
        already_assigned = set(self.search([
            ("shift_date", "=", slot.shift_date),
            ("employee_id", "!=", False),
            ("state", "not in", ("cancelled",)),
            ("id", "!=", slot.id),
        ]).mapped("employee_id").ids)

        # Pre-fetch exclusions for this site/client
        exclusion_model = self.env["security.guard.exclusion"]
        excluded_guard_ids = set()
        if site_id or partner_id:
            excluded_guard_ids = set(exclusion_model.search([
                ("active", "=", True),
                "|",
                ("site_id", "=", site_id),
                ("partner_id", "=", partner_id),
            ]).mapped("employee_id").ids)

        eligible = []
        for employee in all_guards:
            # Guard on leave
            if employee.id in guards_on_leave:
                continue
            # Already assigned elsewhere
            if employee.id in already_assigned:
                continue
            # Excluded from site/client
            if employee.id in excluded_guard_ids:
                continue
            # Grade check
            if min_grade_seq > 0:
                emp_grade_seq = employee.security_grade_id.sequence if employee.security_grade_id else 0
                if emp_grade_seq < min_grade_seq:
                    continue
            # Reliability score
            if employee.security_reliability_score < min_score:
                continue
            # Certifications
            emp_cert_ids = set(employee.security_certification_ids.ids)
            if required_certs - emp_cert_ids:
                continue
            # Expired certifications (if documents module is installed)
            if hasattr(employee, "get_expired_certification_ids"):
                expired = employee.get_expired_certification_ids()
                if required_certs & expired:
                    continue

            # Check required documents for the post type
            post_type_for_docs = slot.post_id.post_type_id if slot.post_id and slot.post_id.post_type_id else False
            if post_type_for_docs and hasattr(post_type_for_docs, "required_document_type_ids") and post_type_for_docs.required_document_type_ids:
                today = fields.Date.context_today(self)
                doc_model = self.env.get("security.employee.document")
                if doc_model is not None:
                    doc_missing = False
                    for required_type in post_type_for_docs.required_document_type_ids:
                        has_valid_doc = doc_model.search_count([
                            ("employee_id", "=", employee.id),
                            ("document_type_id", "=", required_type.id),
                            ("state", "=", "verified"),
                            "|",
                            ("expiry_date", "=", False),
                            ("expiry_date", ">=", str(today)),
                        ])
                        if not has_valid_doc:
                            doc_missing = True
                            break
                    if doc_missing:
                        continue

            eligible.append((employee, 0))

        return eligible

    def _score_guard(self, slot, employee):
        """Return (score, breakdown_text) for one eligible guard."""
        score = float(employee.security_reliability_score)
        parts = [f"Reliability: {score:.0f}"]

        # Site familiarity bonus
        attendance_model = self.env["security.attendance.record"]
        if slot.shift_date and slot.site_id:
            look_back = slot.shift_date - timedelta(days=45)
            familiarity_count = attendance_model.search_count([
                ("employee_id", "=", employee.id),
                ("site_id", "=", slot.site_id.id),
                ("shift_date", ">=", look_back),
                ("shift_date", "<", slot.shift_date),
                ("status", "in", ["present", "late", "early_leave"]),
            ])
            if familiarity_count > 0:
                score += 20
                parts.append(f"+20 site familiarity ({familiarity_count} recent shifts)")

        # Grade bonus (guard is better-qualified than minimum)
        if slot.post_id.post_type_id.min_grade_id and employee.security_grade_id:
            min_seq = slot.post_id.post_type_id.min_grade_id.sequence
            emp_seq = employee.security_grade_id.sequence
            if emp_seq > min_seq:
                score += 10
                parts.append("+10 above minimum grade")

        # Fairness penalty (shifts already in this batch)
        if slot.batch_id:
            shifts_this_period = self.search_count([
                ("batch_id", "=", slot.batch_id.id),
                ("employee_id", "=", employee.id),
                ("state", "not in", ("cancelled",)),
                ("id", "!=", slot.id),
            ])
            penalty = min(shifts_this_period * 5, 30)
            if penalty > 0:
                score -= penalty
                parts.append(f"-{penalty} fairness ({shifts_this_period} shifts this period)")

        # AWOL / absence penalty
        attendance_model_avail = self.env["security.attendance.record"]
        if slot.shift_date:
            look_back_awol = slot.shift_date - timedelta(days=30)
            awol_count = attendance_model_avail.search_count([
                ("employee_id", "=", employee.id),
                ("shift_date", ">=", look_back_awol),
                ("absence_type", "=", "awol"),
            ])
            if awol_count > 0:
                penalty = min(awol_count * 10, 30)
                score -= penalty
                parts.append(f"-{penalty} AWOL in last 30 days ({awol_count}x)")

        return max(0.0, score), " | ".join(parts)
