{
    "name": "Security Operations",
    "summary": "Security posts, site requirements, shift templates, and roster slots",
    "version": "19.0.1.0.0",
    "category": "Human Resources",
    "author": "Winston Zulu",
    "license": "LGPL-3",
    "depends": ["security_base", "contacts"],
    "data": [
        "security/ir.model.access.csv",
        "security/security_operations_security.xml",
        "data/security_operations_cron.xml",
        "data/security_operations_defaults.xml",
        "views/security_operations_menu.xml",
        "views/security_roster_wizard_views.xml",
        "views/security_roster_reject_wizard_views.xml",
        "views/security_site_setup_wizard_views.xml",
        "views/security_operations_views.xml",
        "views/security_client_contract_views.xml",
        "views/res_partner_sites_views.xml",
        "views/security_roster_signoff_views.xml",
        "views/security_guard_availability_views.xml",
        "views/security_demand_plan_views.xml",
        "views/ops_dashboard_actions.xml",
        "views/security_duplicate_views.xml",
        "wizards/security_roster_team_import_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "security_operations/static/src/css/ops_dashboard.css",
            "security_operations/static/src/css/site_hub.css",
            "security_operations/static/src/css/clients_sites_mega_menu.css",
            "security_operations/static/src/css/contract_workspace.css",
            "security_operations/static/src/css/client_sites_workbench.css",
            "security_operations/static/src/css/contracts_dashboard.css",
            "security_operations/static/src/xml/ops_dashboard.xml",
            "security_operations/static/src/xml/site_hub.xml",
            "security_operations/static/src/xml/clients_sites_mega_menu.xml",
            "security_operations/static/src/xml/contract_workspace.xml",
            "security_operations/static/src/xml/client_sites_workbench.xml",
            "security_operations/static/src/xml/contracts_dashboard.xml",
            "security_operations/static/src/js/ops_dashboard.js",
            "security_operations/static/src/js/site_hub.js",
            "security_operations/static/src/js/clients_sites_mega_menu.js",
            "security_operations/static/src/js/contract_workspace.js",
            "security_operations/static/src/js/client_sites_workbench.js",
            "security_operations/static/src/js/contracts_dashboard.js",
        ],
    },
    "installable": True,
    "application": False,
}
