"""
DogForce XLSX Data Extractor — outputs proper Python (not JSON) literals.
Run: python3 scripts/extract_dogforce_data.py
"""
import os, re, sys
from pathlib import Path
from pprint import pformat

try:
    import openpyxl
except ImportError:
    sys.exit("pip install openpyxl")

BASE = Path(__file__).parent.parent
DATA_DIR = BASE / "dogforce_data"
OUT_FILE = BASE / "custom_addons" / "security_dogforce_data" / "dogforce_extracted_data.py"

STRIP_FIELDS = {
    "ssnid","identification_id","passport_id","private_street","private_city",
    "private_zip","private_state_id","private_country_id","private_phone",
    "private_email","private_info","emergency_contact","emergency_phone",
    "bank_account","iban","bic","visa_no","permit_no","visa_expire",
    "certificate","study_field","study_school","km_home_work","barcode","pin",
    "ssc_number","tax_number","security_ssc_number","security_tax_number",
    "security_bank_name","security_bank_account_number",
    "security_emergency_contact_name","security_emergency_contact_phone",
    "security_emergency_contact_relationship","security_home_location",
    "contract_wage","wage","hourly_cost","national_id","avatar 128","image 128",
    "cover image",
}

def is_sensitive(col):
    return any(s in str(col).lower().strip() for s in STRIP_FIELDS)

def clean_val(val):
    if val is None: return None
    if isinstance(val, bool): return val
    s = str(val).strip()
    if s in ("","False","None","FALSE","false"): return None
    if s in ("True","TRUE","true"): return True
    try:
        if "." not in s: return int(s)
        return float(s)
    except (ValueError, TypeError): pass
    return s

def read_xlsx(path):
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    wb.close()
    if not rows: return [], []
    headers = [str(h).strip() if h is not None else f"col_{i}" for i, h in enumerate(rows[0])]
    data = []
    for row in rows[1:]:
        if all(v is None for v in row): continue
        rec = {}
        for h, v in zip(headers, row):
            if is_sensitive(h): continue
            c = clean_val(v)
            if c is not None: rec[h] = c
        if rec: data.append(rec)
    return headers, data

TARGETS = [
    ("Contact (res.partner).xlsx",                                    "res_partner"),
    ("Department (hr.department).xlsx",                               "hr_department"),
    ("Job Position (hr.job).xlsx",                                    "hr_job"),
    ("Resource Working Time (resource.calendar).xlsx",                "resource_calendar"),
    ("Work Location (hr.work.location).xlsx",                         "hr_work_location"),
    ("Skill Type (hr.skill.type).xlsx",                               "hr_skill_type"),
    ("Employee (hr.employee).xlsx",                                   "hr_employee"),
    ("Product (product.template).xlsx",                               "product_template"),
    ("Product Unit of Measure (uom.uom).xlsx",                        "uom_uom"),
    ("Sales Team (crm.team).xlsx",                                    "crm_team"),
    ("Attendance (hr.attendance).xlsx",                               "hr_attendance"),
    ("Sales Order (sale.order).xlsx",                                 "sale_order"),
    ("Departure Reason (hr.departure.reason).xlsx",                   "hr_departure_reason"),
    ("Applicant (hr.applicant).xlsx",                                 "hr_applicant"),
    ("Refuse Reason of Applicant (hr.applicant.refuse.reason).xlsx",  "hr_applicant_refuse_reason"),
]

lines = [
    "# AUTO-GENERATED by scripts/extract_dogforce_data.py — DO NOT EDIT MANUALLY",
    "DOGFORCE_DATA = {}",
    "",
]

for filename, key in TARGETS:
    fpath = DATA_DIR / filename
    if not fpath.exists():
        lines.append(f"# WARNING: {filename} not found")
        continue
    headers, rows = read_xlsx(fpath)
    print(f"  {key}: {len(rows)} rows | cols: {headers[:8]}", file=sys.stderr)
    lines.append(f"# {filename}  ({len(rows)} rows)")
    lines.append(f"# columns: {headers}")
    lines.append(f"DOGFORCE_DATA[{key!r}] = {pformat(rows, width=120, compact=False)}")
    lines.append("")

OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"\n✓ Wrote {OUT_FILE}", file=sys.stderr)
