{
    "name": "Security Billing",
    "summary": "Security company client contracts, billing plans, and invoice generation",
    "version": "19.0.1.0.0",
    "category": "Accounting",
    "author": "Winston Zulu",
    "license": "LGPL-3",
    "depends": ["security_payroll_core", "security_operations", "security_attendance", "account"],
    "data": [
        "data/ir_sequence.xml",
        "data/security_billing_cron.xml",
        "data/document_template_data.xml",
        "security/ir.model.access.csv",
        "views/revenue_dashboard_actions.xml",
        "views/security_billing_views.xml",
        "views/security_billing_wizard_views.xml",
        "views/security_document_designer_views.xml",
        "views/res_partner_views.xml",
        "reports/security_invoice_report.xml",
        "reports/security_invoice_aging_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "security_billing/static/src/js/billing_dashboard.js",
            "security_billing/static/src/xml/billing_dashboard.xml",
            "security_billing/static/src/css/billing_command_center.css",
            "security_billing/static/src/css/revenue_dashboard.css",
            "security_billing/static/src/xml/revenue_dashboard.xml",
            "security_billing/static/src/js/revenue_dashboard.js",
            "security_billing/static/src/css/document_designer.css",
            "security_billing/static/src/xml/document_designer.xml",
            "security_billing/static/src/js/document_designer.js",
        ],
    },
    "installable": True,
    "application": False,
}
