# -*- coding: utf-8 -*-
{
    "name": "DeployGuard Zambia Demo Environment",
    "summary": "Full Zambia operational demo data, vehicles, equipment, attendance, and payroll rules for Sentinel Security Zambia Ltd",
    "version": "19.0.1.0.0",
    "category": "Security/Demo",
    "author": "Winston Zulu",
    "license": "LGPL-3",
    "depends": [
        "security_base",
        "security_operations",
        "security_attendance",
        "security_leave",
        "security_l10n_zm",
        "security_payroll_core",
        "security_loans",
        "security_discipline",
        "security_billing",
        "security_client_reports",
        "security_equipment",
        "security_fleet",
        "security_ai_engine",
        "security_shift_planner",
    ],
    "data": [],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "auto_install": False,
}
